gui-onssl-logstash-<_KEY_>:
  image: ${env.DOCKER_REGISTRY}/guionssl.web:${gui-onssl.version}
  environment:
    SITE_CRT_FILE: 'nginx-selfsigned'
    GUI_FWK_WEB_SERVER_HOST_INTERNAL_IP: <_GUI_FWK_WEB_SERVER_HOST_INTERNAL_IP_>
    GUI_FWK_WEB_SERVER_PORT: <_GUI_FWK_WEB_SERVER_PORT_>
    GUI_FWK_API_SERVER_HOST_INTERNAL_IP: <_GUI_FWK_API_SERVER_HOST_INTERNAL_IP_>
    GUI_FWK_API_SERVER_PORT: <_GUI_FWK_API_SERVER_PORT_>
    GUI_CSR_WEB_SERVER_HOST_INTERNAL_IP: <_GUI_CSR_WEB_SERVER_HOST_INTERNAL_IP_>
    GUI_CSR_WEB_SERVER_PORT: <_GUI_CSR_WEB_SERVER_PORT_>
    GUI_CSR_API_SERVER_HOST_INTERNAL_IP: <_GUI_CSR_API_SERVER_HOST_INTERNAL_IP_>
    GUI_CSR_API_SERVER_PORT: <_GUI_CSR_API_SERVER_PORT_>
    GUI_ITM_WEB_SERVER_HOST_INTERNAL_IP: <_GUI_ITM_WEB_SERVER_HOST_INTERNAL_IP_>
    GUI_ITM_WEB_SERVER_PORT: <_GUI_ITM_WEB_SERVER_PORT_>
    GUI_ITM_API_SERVER_HOST_INTERNAL_IP: <_GUI_ITM_API_SERVER_HOST_INTERNAL_IP_>
    GUI_ITM_API_SERVER_PORT: <_GUI_ITM_API_SERVER_PORT_>
    GUI_JMR_WEB_SERVER_HOST_INTERNAL_IP: <_GUI_JMR_WEB_SERVER_HOST_INTERNAL_IP_>
    GUI_JMR_WEB_SERVER_PORT: <_GUI_JMR_WEB_SERVER_PORT_>
    GUI_JMR_API_SERVER_HOST_INTERNAL_IP: <_GUI_JMR_API_SERVER_HOST_INTERNAL_IP_>
    GUI_JMR_API_SERVER_PORT: <_GUI_JMR_API_SERVER_PORT_>
    GUI_OPC_WEB_SERVER_HOST_INTERNAL_IP: <_GUI_OPC_WEB_SERVER_HOST_INTERNAL_IP_>
    GUI_OPC_WEB_SERVER_PORT: <_GUI_OPC_WEB_SERVER_PORT_>
    GUI_OPC_API_SERVER_HOST_INTERNAL_IP: <_GUI_OPC_API_SERVER_HOST_INTERNAL_IP_>
    GUI_OPC_API_SERVER_PORT: <_GUI_OPC_API_SERVER_PORT_>    
    GUI_IAR_WEB_SERVER_HOST_INTERNAL_IP: <_GUI_IAR_WEB_SERVER_HOST_INTERNAL_IP_>
    GUI_IAR_WEB_SERVER_PORT: <_GUI_IAR_WEB_SERVER_PORT_>
    GUI_IAR_API_SERVER_HOST_INTERNAL_IP: <_GUI_IAR_API_SERVER_HOST_INTERNAL_IP_>
    GUI_IAR_API_SERVER_PORT: <_GUI_IAR_API_SERVER_PORT_>
    GUI_OPR_WEB_SERVER_HOST_INTERNAL_IP: <_GUI_OPR_WEB_SERVER_HOST_INTERNAL_IP_>
    GUI_OPR_WEB_SERVER_PORT: <_GUI_OPR_WEB_SERVER_PORT_>
    GUI_OPR_API_SERVER_HOST_INTERNAL_IP: <_GUI_OPR_API_SERVER_HOST_INTERNAL_IP_>
    GUI_OPR_API_SERVER_PORT: <_GUI_OPR_API_SERVER_PORT_>
    GUI_STG_WEB_SERVER_HOST_INTERNAL_IP: <_GUI_STG_WEB_SERVER_HOST_INTERNAL_IP_>
    GUI_STG_WEB_SERVER_PORT: <_GUI_STG_WEB_SERVER_PORT_>
    GUI_STG_API_SERVER_HOST_INTERNAL_IP: <_GUI_STG_API_SERVER_HOST_INTERNAL_IP_>
    GUI_STG_API_SERVER_PORT: <_GUI_STG_API_SERVER_PORT_>
    GUI_SBM_WEB_SERVER_HOST_INTERNAL_IP: <_GUI_SBM_WEB_SERVER_HOST_INTERNAL_IP_>
    GUI_SBM_WEB_SERVER_PORT: <_GUI_SBM_WEB_SERVER_PORT_>
    GUI_SBM_API_SERVER_HOST_INTERNAL_IP: <_GUI_SBM_API_SERVER_HOST_INTERNAL_IP_>
    GUI_SBM_API_SERVER_PORT: <_GUI_SBM_API_SERVER_PORT_>
    GUI_LPM_WEB_SERVER_HOST_INTERNAL_IP: <_GUI_LPM_WEB_SERVER_HOST_INTERNAL_IP_>
    GUI_LPM_WEB_SERVER_PORT: <_GUI_LPM_WEB_SERVER_PORT_>
    GUI_LPM_API_SERVER_HOST_INTERNAL_IP: <_GUI_LPM_API_SERVER_HOST_INTERNAL_IP_>
    GUI_LPM_API_SERVER_PORT: <_GUI_LPM_API_SERVER_PORT_>
    FWK_URL_WEB_SERVER_PATH: '<_GUI_HTTP_PROCOTOL_>://<_GUI_ONSSL_SERVER_HOST_>/fwk'
    GUI_SERVER_NAME: <_GUI_ONSSL_SERVER_HOST_>    
    KIBANA_WEB_SERVER_HOST_INTERNAL_IP: <_KIBANA_WEB_SERVER_HOST_INTERNAL_IP_>
    KIBANA_WEB_SERVER_PORT: <_KIBANA_PORT_>
    KIBANA_WEB_SERVER_PORT_ON_SSL: <_KIBANA_PORT_ON_SSL_>
    GRAFANA_WEB_SERVER_HOST_INTERNAL_IP: <_GRAFANA_WEB_SERVER_HOST_INTERNAL_IP_>
    GRAFANA_WEB_SERVER_PORT: <_GRAFANA_FOR_GUI_PORT_>
    GRAFANA_USER: <_GRAFANA_USER_>
    GRAFANA_PASS: <_GRAFANA_PASSWORD_>
    GRAFANA_TENANTS_PORT_START: <_GRAFANA_TENANTS_PORT_START_>
    ConnectionStrings_FwkConnection: 'root:<_MYSQL_ROOT_PASSWORD_>@tcp(<_MYSQL_GUI_SERVER_HOST_>:<_MYSQL_GUI_SERVER_PORT_>)/dbframework'
    TZ: <_DEPLOYMENT_TIMEZONE_>
  volumes:
    - type: bind
      source: <_NGLM_GUI_RUNTIME_>/SSLcertificates
      target: /etc/nginx/certs
  deploy:
    restart_policy:
      condition: <_DOCKER_RESTART_POLICY_>
      delay: 5s
      max_attempts: 3
      window: 120s
    mode: replicated
    replicas: 1
    placement:
      constraints:
        - engine.labels.hostname == <_GUI_ONSSL_SERVER_HOST_>
  networks:
    - outside