lpm-web-<_KEY_>:
  image: ${env.DOCKER_REGISTRY}lpm.web:${gui-lpm.version}
  environment:
    lpm_api_server_path: "<_GUI_HTTP_PROCOTOL_>://<_GUI_LPM_API_FULL_PATH_>"
    lpm_fwk_api_server_path: "<_GUI_HTTP_PROCOTOL_>://<_GUI_FWK_API_FULL_PATH_>"
    lpm_api_server_path_for_upload_files: "<_GUI_HTTP_PROCOTOL_>://<_GUI_LPM_API_FULL_PATH_>/file/flowupload"
    LPM_URL_ELASTICSEARCH_PATH: "<_GUI_HTTP_PROCOTOL_>://<_MASTER_ESROUTER_HOST_>:<_MASTER_ESROUTER_PORT_>"
    URL_KIBANA_PATH: "<_GUI_HTTP_PROCOTOL_>://<_GUI_ONSSL_SERVER_HOST_>:<_KIBANA_PORT_ON_SSL_>"
    URL_GRAFANA_PATH: "<_GUI_HTTP_PROCOTOL_>://<_GUI_ONSSL_SERVER_HOST_>"
    URL_GUIMANAGER_API: "http://<_GUIMANAGER_HOST_>:<_GUIMANAGER_PORT_>/nglm-guimanager/"
    GRAFANA_FOR_GUI_PORT: <_GRAFANA_FOR_GUI_PORT_>
    GRAFANA_TENANTS_PORT_START: <_GRAFANA_TENANTS_PORT_START_> 
    WEB_URL_ALLOW: "<_WEB_URL_ALLOW_>"
    DIALOG_TEMPLATE_SMS: '<_DIALOG_TEMPLATE_SMS_>'
    DIALOG_TEMPLATE_EMAIL: '<_DIALOG_TEMPLATE_EMAIL_>'
    DIALOG_TEMPLATE_PUSH: '<_DIALOG_TEMPLATE_PUSH_>'
    DIALOG_TEMPLATE_GENERIC: '<_DIALOG_TEMPLATE_GENERIC_>'
    EXPORT_IMPORT_ENABLED: '<_LPM_EXPORT_IMPORT_ENABLED_>'
    SHOW_CHALLENGES: '<_LPM_SHOW_CHALLENGES_>'
    SHOW_MISSIONS: '<_LPM_SHOW_MISSIONS_>'
    SHOW_LEADERBOARDS: '<_LPM_SHOW_LEADERBOARDS_>'
    DATE_TIME_FORMAT: "<_DATE_TIME_FORMAT_>"
    DATE_TIME_Z_FORMAT: "<_DATE_TIME_Z_FORMAT_>"
    DATE_FORMAT: "<_DATE_FORMAT_>"
    TIME_FORMAT: "<_TIME_FORMAT_>"
    DISPLAY_DATE_TIME_FORMATS: "<_DISPLAY_DATE_TIME_FORMATS_>"
    DISPLAY_DATE_FORMATS: "<_DISPLAY_DATE_FORMATS_>"
    DISPLAY_TIME_FORMATS: "<_DISPLAY_TIME_FORMATS_>"
    GANTT_ENABLED: '<_LPM_GANTT_ENABLED_>'
    APPROVAL_MODE_ENABLED: '<_APPROVAL_MODE_ENABLED_>'
    TZ: <_DEPLOYMENT_TIMEZONE_>
    LPM_WEB_PORT: <_PORT_>
  deploy:
    restart_policy:
      condition: <_DOCKER_RESTART_POLICY_>
      delay: 5s
      max_attempts: 3
      window: 120s
    mode: replicated
    replicas: 1
    placement:
      constraints:
        - engine.labels.hostname == <_GUI_LPM_WEB_SERVER_HOST_>
  networks:
    - outside

